### ISSUE TITLE
Migration file not moved

### ISSUE THREAD

**Issue by Themesfa** [ARCANEDEV/LaravelSettings#10]
- Laravel Version: 5.5.*
- PHP Version: 7.1

hi . i'm try to use database driver but in provider you do not include database migration option.
that means the database file not automatically moved to laravel migration folder .
pleas fix that .

**Comment by Themesfa** [comment]
i fix that by adding "!" on first of line 51 in SettingsServiceProvider.php file. like that:
**`!SettingsManager::$runsMigrations ? $this->loadMigrations() : $this->publishMigrations();`**
after that i run vendor:publish again and now database file moved to laravel migration file .

**Comment by arcanedev-maroc** [comment]
If you want to move the migrations into the database folder.

Set the value of `SettingsManager::$runsMigrations` to `false` in your `AppServiceProvider` for example.
