### ISSUE TITLE
how to set nested settings ?

### ISSUE THREAD

**Issue by Themesfa** [ARCANEDEV/LaravelSettings#16]
- Laravel Version: 5.5.*
- PHP Version: 7.1.*

i want to store settings from my form with this inputs : 

```blade
<input name="settings[header][logo]" value="images/logo.png">
<input name="settings[header][type]" value="3">
...
```

how i can set/get settings like this ?

**Comment by arcanedev-maroc** [comment]
Something like this ?

**routes/web.php**
```php
Route::get('form', function () {
    return view('form');
});

Route::post('form', function (\Illuminate\Http\Request $request) {
    settings()->set(
        $request->get('settings')
    );

    // SAVE THE SETTINGS MANUALLY OR WITH MIDDLEWARE
});
```

**resources/views/form.blade.php**

```blade
<form action="/form" method="POST">
    {{ csrf_field() }}

    <input name="settings[header][logo]" value="images/logo.png">
    <input name="settings[header][type]" value="3">

    <button type="submit">Submit</button>
</form>
```

You can get a specific setting like this:

```php
$header = settings()->get('header'); // returns ['log' => 'images/logo.png', 'type' => 3]

// OR
$type = settings()->get('header.type');
```

Check the documentation: https://github.com/ARCANEDEV/LaravelSettings/blob/master/_docs/3-Usage.md

**Comment by Themesfa** [comment]
well but i want to get header settings like this : 
in form : 
`<input name="settings[header][type]" value="3">`
in app : 
`$type= settings()->set('settings.header.type');`

i make input dynamic and it should be like this to work . 
but the first part of input name not saving . i mean the part of the name that is 'settings' not saving and just child names saving in database . how i can save child with parents ?

**Comment by arcanedev-maroc** [comment]
You have two options:

```php
// OPTION 1
$settings = $request->get('settings');

settings()->set(compact('settings'));

// OPTION 2    
settings()->set($request->only('settings'));
```
