### ISSUE TITLE
Target [Arcanedev\LaravelSettings\Contracts\Manager] is not instantiable.

### ISSUE THREAD

**Issue by Themesfa** [ARCANEDEV/LaravelSettings#17]
- Laravel Version: 5.5.*
- PHP Version: 7.1.*

i want to get settings in config/mail.php but this error happens : 

> Target [Arcanedev\LaravelSettings\Contracts\Manager] is not instantiable.

i'm use this code to get settings : 
`settings()->get('key')`

why i'm get this error ?

**Comment by arcanedev-maroc** [comment]
I don't recommend to do that and this is why: https://laravel.com/docs/5.6/configuration#configuration-caching

Only use the `env()` in your config files, if you want to make configs more dynamic, use a **ServiceProviders** especially the `boot()` method.

Revert the changes in your config files and do this instead:

```php
<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        $this->app['config']->set('main.driver', settings()->get('mail.driver', 'smtp'));

        // Do any other settings...
    }

    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        //
    }
}
```
