### ISSUE TITLE
set foreign key for user_id

### ISSUE THREAD

**Issue by Themesfa** [ARCANEDEV/LaravelSettings#18]
- Laravel Version: 5.6
- PHP Version: 7.2

I set a foreign key for `user_id ` references `id` on `users ` with this code in migration file:

> $table->foreign('user_id')->references('id')->on('users')->onDelete('cascade')->onUpdate('cascade');

i want to delete user settings when user deleted. but there is a problem with default settings that users_id is  0 . because user_id 0 is not exists in `users ` table and it just a default value for normal settings and i get error when i want to set a normal setting . 
how i can fix that ? should i use a second table for normal settings and how i do that ?

**Comment by arcanedev-maroc** [comment]
You can solve your problem by using the Model's event: https://laravel.com/docs/5.6/eloquent#events

**Comment by Themesfa** [comment]
you mean i must remove user settings by create a listener and fire an event on delete a user to remove all setting related to it ?

**Comment by arcanedev-maroc** [comment]
Yes, something like [this listener](https://github.com/ARCANEDEV/LaravelAuth/blob/master/src/Listeners/Users/DetachingRoles.php) handled when `deleting` a user.
