### ISSUE TITLE
Support for Laravel 8.x

### ISSUE THREAD

**Issue by rhurling** [ARCANEDEV/LaravelSettings#26]
- LaravelSettings Version: 7.x
- Laravel Version: 8.x
- PHP Version: 7.4

### Description:
Please add support for Laravel 8.x. This is the last of my dependencies not supporting Laravel 8.

### Steps To Reproduce:
Try to install or update to Laravel 8 and this package.

**Comment by arcanedev-maroc** [comment]
Done :+1:
